name: 'Sample: Alpine/Packer/QEMU'

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - name: Build Alpine raw disk image
      run: |
        apk update
        apk add git
        git --version > git-version.txt

    - name: Upload disk image
      uses: actions/upload-artifact@v2
      with:
        name: git-version
        path: git-version.txt