name: 'Sample: Alpine/Packer/QEMU'

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: /samples    
    container:
      image: raonigabriel/iac-packer-qemu

    steps:

    - name: Generate SSH keypair
      run:  |
        mkdir -p ~/.ssh
        cat /dev/zero | ssh-keygen -b 4096 -q -N "" -f ~/.ssh/id_rsa
    - name: Copy public key as authorized_keys
      run: cp ~/.ssh/id_rsa.pub /samples/authorized_keys
    - name: Build Alpine raw disk image
      run: packer build alpine.json 2>/dev/null
    - name: Compact the disk image
      run: GZIP=-9 tar -czf images/alpine.tar.gz disk.raw -C images/alpine
    - name: Upload keypair
      uses: actions/upload-artifact@v2
      with:
        name: keypair
        path: |
          ~/.ssh/id_rsa
          ~/.ssh/id_rsa.pub
    - name: Upload disk image
      uses: actions/upload-artifact@v2
      with:
        name: alpine-image
        path: /samples/images/alpine.tar.gz
