name: 'Sample: Alpine/Packer/QEMU'

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: raonigabriel/iac-packer-qemu

    steps:

    - name: Show user info
      run:  |
        echo "uid=$(id -u)"
        echo "gid=$(id -g)"
    - name: Generate SSH keypair
      run:  cat /dev/zero | ssh-keygen -b 4096 -q -N "" &>/dev/null
    - name: Copy public key as authorized_keys
      run: cp ~/.ssh/id_rsa.pub /samples/authorized_keys
    - name: Build Alpine raw disk image
      run: packer build alpine.json 2>/dev/null
    - name: Compact the disk image
      run: GZIP=-9 tar -czf images/alpine.tar.gz disk.raw -C images/alpine
    - name: Upload keypair
      uses: actions/upload-artifact@v2
      with:
        name: keypair
        path: |
          ~/.ssh/id_rsa
          ~/.ssh/id_rsa.pub
    - name: Upload disk image
      uses: actions/upload-artifact@v2
      with:
        name: alpine-image
        path: images/alpine.tar.gz